AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaFunctionContainers:
    Properties:
      CodeUri: s3://sam-temp-bucket-zim/d44aee7e69c5db96801f3fa68dea2f09
      Environment:
        Variables:
          TABLE_NAME:
            Ref: dbTableContainers
      Events:
        Stream:
          Properties:
            BatchSize: 100
            StartingPosition: LATEST
            Stream:
              Fn::GetAtt:
              - kinesisEventStream
              - Arn
          Type: Kinesis
      Handler: index.handler
      Policies:
      - Ref: dbPolicyTables
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
  LambdaFunctionRules:
    Properties:
      CodeUri: s3://sam-temp-bucket-zim/b6ed8f93e594c3cfd50eade5b46d898a
      Environment:
        Variables:
          TABLE_NAME:
            Ref: dbTableRules
      Events:
        CreateRule:
          Properties:
            Method: post
            Path: /rules
          Type: Api
      Handler: create.create
      Policies:
      - Ref: dbPolicyTables
      Runtime: python3.7
    Type: AWS::Serverless::Function
  dbPolicyTables:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - dynamodb:BatchGet*
          - dynamodb:DescribeStream
          - dynamodb:DescribeTable
          - dynamodb:Get*
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:BatchWrite*
          - dynamodb:CreateTable
          - dynamodb:Delete*
          - dynamodb:Update*
          - dynamodb:PutItem
          Effect: Allow
          Resource:
          - '*'
        Version: 2012-10-17
    Type: AWS::IAM::ManagedPolicy
  dbTableContainers:
    Properties:
      PrimaryKey:
        Name: EventId
        Type: String
    Type: AWS::Serverless::SimpleTable
  dbTableRules:
    Properties:
      PrimaryKey:
        Name: RuleId
        Type: String
    Type: AWS::Serverless::SimpleTable
  kinesisEventStream:
    Properties:
      ShardCount: 1
    Type: AWS::Kinesis::Stream
Transform: AWS::Serverless-2016-10-31
